# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhiHuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('category_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ZhiHuCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question_url', models.CharField(max_length=300)),
                ('answer_vote', models.CharField(max_length=200)),
                ('answer_url', models.CharField(max_length=200, unique=True)),
                ('answer_content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('author_url', models.CharField(max_length=300)),
                ('author_img', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycollections.ZhiHuCategory')),
            ],
        ),
    ]
