# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zhihucategory',
            options={'verbose_name': '知乎收藏夹'},
        ),
        migrations.AlterModelOptions(
            name='zhihucollection',
            options={'verbose_name': '知乎回答'},
        ),
        migrations.AlterField(
            model_name='zhihucollection',
            name='answer_content',
            field=models.TextField(verbose_name='回答内容'),
        ),
        migrations.AlterField(
            model_name='zhihucollection',
            name='answer_url',
            field=models.CharField(max_length=200, unique=True, verbose_name='回答地址'),
        ),
        migrations.AlterField(
            model_name='zhihucollection',
            name='answer_vote',
            field=models.CharField(max_length=200, verbose_name='得票数'),
        ),
        migrations.AlterField(
            model_name='zhihucollection',
            name='author',
            field=models.CharField(max_length=200, verbose_name='回答作者'),
        ),
        migrations.AlterField(
            model_name='zhihucollection',
            name='author_img',
            field=models.CharField(max_length=300, verbose_name='作者头像'),
        ),
        migrations.AlterField(
            model_name='zhihucollection',
            name='author_url',
            field=models.CharField(max_length=300, verbose_name='回答作者地址'),
        ),
        migrations.AlterField(
            model_name='zhihucollection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycollections.ZhiHuCategory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='zhihucollection',
            name='question_url',
            field=models.CharField(max_length=300, verbose_name='问题地址'),
        ),
        migrations.AlterField(
            model_name='zhihucollection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='问题'),
        ),
    ]
