# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0002_auto_20170513_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zhihucategory',
            options={'verbose_name': '知乎收藏夹', 'verbose_name_plural': '知乎收藏夹'},
        ),
        migrations.AlterModelOptions(
            name='zhihucollection',
            options={'verbose_name': '知乎回答', 'verbose_name_plural': '知乎回答'},
        ),
    ]
